name: Pull Request snippet analysis

on:
  pull_request:
    branches: [ "main" ]
jobs:
  snippet_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: synopsys-sig-community/blackduck-snippet-scanner@main
      with:
        blackduck_url: ${{secrets.BLACKDUCK_SERVER_URL}}
        blackduck_apiToken: ${{secrets.BLACKDUCK_ACCESS_TOKEN}}
        blackduck_outputFile: ${{github.workspace}}/blackduck-snippet.sarif.json
        blackduck_log_level: DEBUG
        github_url: ""
        github_apiToken: ${{secrets.GITHUB_TOKEN}}
        github_repo: ${{github.repository}}
        github_pull_request_id: ${{github.event.pull_request.number}}
        github_prComment: false
        github_prCommentGroupped: true
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{github.workspace}}/blackduck-snippet.sarif.json
      continue-on-error: true
    - name: Archive scanning results
      uses: actions/upload-artifact@v4
      with:
        name: bd-snippet-scan-results
        path: ${{github.workspace}}/blackduck-snippet.sarif.json
      continue-on-error: true


